name: Continuous Testing
on: [push]

jobs:
  phpstan:
    name: Static Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          extensions: bcmath
      - run: composer install
      - run: vendor/bin/phpstan analyse
  phpmd:
    name: Mess Detector
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          extensions: bcmath
      - run: composer install
      - run: vendor/bin/phpmd src/ github phpmd.ruleset.xml
  phpunit:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          extensions: bcmath
          coverage: xdebug
      - run: composer install
      - run: vendor/bin/phpunit tests/ --coverage-clover clover.xml --log-junit junit.xml
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}