name: Continuous Testing
on: [push]

jobs:
  phpstan:
    name: Static Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          extensions: bcmath
      - run: composer install
      - run: vendor/bin/phpstan analyse
  phpmd:
    name: Mess Detector
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          extensions: bcmath
      - run: composer install
      - run: vendor/bin/phpmd src/ github phpmd.ruleset.xml